sudo: false
language: node_js
node_js: node
notifications:
  disabled: true

before_install:
- npm i -g now@latest

install: npm install

deploy:
  provider: script
  script: npm run deploy
  on:
    tags: true
